
# Decap CMS Config
backend:
  name: "git-gateway"
  branch: "main" 
  site_url: https://brotherstaxi.netlify.app
  local_backend: true 
  debug: true


media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/_posts/blog"
    create: true
    slug: "{{slug}}"
    fields:
      [{ label: "Title", name: "title", widget: "string" },
      { label: "Description", name: "description", widget: "string" },
      { label: "Date", name: "date", widget: "datetime" },
      { label: "Thumbnail", name: "thumbnail", widget: "image" },
      { label: "Body", name: "body", widget: "markdown" }]


  - name: "vehicles"
    label: "Vehicles"
    folder: "src/_vehicles/vehicle"
    create: true
    slug: "{{slug}}"
    fields:
      [{ label: "Title", name: "title", widget: "string" },
      { label: "Category", name: "category", widget: "select", options: ['SUV','SIDAN','PASSANGER'] },
      { label: "Image", name: "image", widget: "image" },
      { label: "Description", name: "description", widget: "markdown" }]

      